name: Linters

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PYTHON_VERSION: 3.11

jobs:

  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ env.PYTHON_VERSION }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 mypy pylint
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install -r requirements.txt

      - name: python-isort
        uses: isort/isort-action@v1.1.0

      - name: black
        uses: psf/black@stable

      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: flake8 --max-line-length=88 --extend-ignore=E203 job_scraper

      - name: Run mypy
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: mypy
          run: mypy --install-types --non-interactive job_scraper/

      - name: Run pylint
        run: pylint job_scraper --rcfile=pyproject.toml
